[package]
name = "my-slack-resource"
version = "0.1.0"
authors = ["François Mockers <mockersf@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
concourse-resource = { git = "https://github.com/mockersf/concourse-resource-rs" }
slack_push = { git = "https://github.com/mockersf/slack-push" }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
urlencoding = "1.0"
